// src/ui/episodeView/index.tsx
import { h } from "../../lib/jsx/runtime";
import { createSignal, bind } from "../../lib/jsx/reactive";
import { router } from "../../lib/router";
import { Episode } from "../episode";
import { PageControls } from "../pageControls";
import { SourcePanel } from "../sourcePanel";
import { kitsu, KitsuAnime, KitsuEpisode } from "../../lib/kitsu";
import { API } from "../../app";

const [visibleEpisodes, setVisibleEpisodes, subscribeVisibleEpisodes] =
  createSignal<KitsuEpisode[]>([]);

export function EpisodeView({
  anime,
  sourcepanel_callback,
}: {
  anime: KitsuAnime;
  sourcepanel_callback: any;
}) {
  episodeHandler(anime, 0);

  return (
    <div>
      {bind(
        [visibleEpisodes, setVisibleEpisodes, subscribeVisibleEpisodes],
        (value) => (
          <div
            class="h-fit w-full grid grid-cols-1
            lg:grid-cols-4
            gap-4"
          >
            {value.map((episode: KitsuEpisode, index) => (
              <Episode
                episode={episode}
                index={index}
                sourcepanel_callback={sourcepanel_callback}
              />
            ))}
          </div>
        ),
      )}
      <PageControls
        className="mt-6 ml-auto"
        totalPages={Math.ceil(anime.attributes.episodeCount! / 16)}
        currentPage={1}
        callback={(page) => episodeHandler(anime, page - 1)}
      />
    </div>
  );
}

async function episodeHandler(anime: KitsuAnime, page: number) {
  const episodesPerPage = 16;

  const [episodes, episodesProgress] = await Promise.all([
    await kitsu.getEpisodesPagination(anime.id, page, episodesPerPage),
    await API.getAnimeProgress(
      anime.id,
      page * episodesPerPage,
      page * episodesPerPage + episodesPerPage,
    ),
  ]);

  episodes.map((episode) => {
    const progress = episodesProgress.find(
      (progress) => progress.episode === episode.attributes.number,
    );
    episode.leftoff = progress ? progress.leftoff : 0;
  });

  setVisibleEpisodes(episodes);

  router.route("/anime/updateEpisodeProgress", (query: any) => {
    if (query.kitsu_id !== anime.id) return;

    const episodeTarget = visibleEpisodes().find(
      (episode) => episode.attributes.number === parseInt(query.episode),
    );

    if (!episodeTarget) return;

    episodeTarget.leftoff = query.leftoff;
    setVisibleEpisodes(visibleEpisodes());
  });
}

// src/lib/components/common/Episodeview.svelte
<script lang="ts">
    import Episode from "$lib/components/common/Episode.svelte";
    import Pagecontrols from "$lib/components/common/Pagecontrols.svelte";
    import Spinner from "$lib/components/common/Spinner.svelte";
    import { kitsu, type KitsuAnime } from "$lib/kitsu";
    import { getAPIClient } from "$lib/api";
    import { visibleEpisodes, user } from "$lib/stores";
    import { onDestroy } from "svelte";

    const API = getAPIClient();

    let { anime } = $props();

    let isLoading = $state(true);

    $effect(() => {
        episodeHandler(anime, 0);
    });

    async function episodeHandler(anime: KitsuAnime, page: number) {
        isLoading = true;
        const episodesPerPage = 15;

        const [episodesObj, episodesProgress] = await Promise.all([
            await kitsu.getEpisodesPagination(anime.id, page, episodesPerPage),
            $user
                ? await API.getAnimeProgress(
                      anime.id,
                      page * episodesPerPage,
                      page * episodesPerPage + episodesPerPage,
                  )
                : [],
        ]);

        episodesObj.map((episode) => {
            const progress = episodesProgress.find(
                (progress) => progress.episode === episode.attributes.number,
            );
            episode.leftoff = progress ? progress.leftoff : 0;
        });

        visibleEpisodes.set(episodesObj);
        isLoading = false;
    }

    onDestroy(() => {
        visibleEpisodes.set([]);
    });
</script>

<div
    class="h-fit w-full grid grid-cols-1
      lg:grid-cols-5
      gap-4"
>
    {#if isLoading}
        <div class="h-48 col-span-full flex items-center justify-center">
            <Spinner />
        </div>
    {:else if !isLoading && $visibleEpisodes.length === 0}
        <div class="h-full col-span-full flex items-center justify-center">
            <div
                class="w-full py-8 flex flex-col items-center justify-center space-y-1"
            >
                <div class="text-3xl">😕</div>
                <div class="text-lg">No Episodes found</div>
                <div class="text-neutral-500 text-xs">
                    Try coming back later.
                </div>
            </div>
        </div>
    {:else if !isLoading && $visibleEpisodes.length > 0}
        {#each $visibleEpisodes as episode, index}
            <Episode {anime} {episode} {index} />
        {/each}
    {/if}
</div>
<Pagecontrols
    totalPages={Math.ceil(anime.attributes.episodeCount / 15)}
    currentPage={1}
    callback={(page) => episodeHandler(anime, page - 1)}
    class="mt-6 ml-auto"
/>
