// src/ui/newscard/index.tsx
import { h } from "../../lib/jsx/runtime";
import { NewsItem } from "../../lib/anime2you";

export function NewsCard({ news }: { news: NewsItem }) {
  return (
    <div
      class="space-y-2"
      onClick={() => window.electronAPI?.openUrl(news.link)}
    >
      <img
        src={news.thumbnail}
        alt={news.title}
        className="w-full aspect-video object-cover rounded-md"
      />
      <div className="text-sm">{news.title}</div>
      <div className="text-xs text-neutral-500">
        {new Date(news.pubDate!).toLocaleDateString()}
      </div>
    </div>
  );
}

// src/lib/components/common/Newscard.svelte
<script lang="ts">
    let { news } = $props();
</script>

<button
    class="relative flex flex-col text-left outline-hidden group/newscard cursor-pointer"
    onclick={() => window.electronAPI?.openUrl(news.link)}
>
    <div class="relative space-y-2">
        <div
            class="w-full aspect-video rounded-lg overflow-hidden outline-offset-2 outline-white group-hover/newscard:outline-2 group-focus-within/newscard:outline-2"
        >
            <img
                src={news.thumbnail}
                alt={news.title}
                class="h-full w-full object-cover transition-transform duration-300 group-hover/newscard:scale-105 group-focus-within/newscard:scale-105"
            />
        </div>
        <div class="text-sm">{news.title}</div>
        <div class="text-xs text-neutral-500">
            {new Date(news.pubDate!).toLocaleDateString()}
        </div>
    </div>
</button>
